spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sentistrength?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Czy026110
    driver-class-name: com.mysql.jdbc.Driver