spring:
  datasource:
    url: jdbc:mysql://124.70.198.102:3306/sentistrength?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 'HaRdEsTnju@123'
    driver-class-name: com.mysql.jdbc.Driver
